name: flutter_clean_architecture_test
description: A new Flutter project.

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ">=2.15.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2
  flutter_hooks: ^0.18.2
  get_it: ^7.2.0
  retrofit: ^3.0.1
  floor: ^1.2.0
  flutter_bloc: ^8.0.1
  equatable: ^2.0.3
  ionicons: ^0.1.2

dev_dependencies:
  build_runner: ^2.1.7
  floor_generator: ^1.2.0
  flutter_test:
    sdk: flutter
  lint: ^1.8.1
  retrofit_generator: ^3.0.1+1

flutter:
  uses-material-design: true